### ISSUE TITLE
Can some versions of Tensorflow cause problems?

### ISSUE THREAD

**Issue by AndroXD** [keijiro/Pix2Pix#10]
Hello Keijiro,
about 2 months ago I trained my own model and exported a .PICT that worked fine with your plugin.
Recently I formatted my hard drive, reinstalled everything, trained a new model and exported a .PICT again, but it throws hundreds of errors when loading it with your plugin, this doesn't happen with the old .PICT.
I don't think the new model is corrupted or anything, it works well outside of Unity.
Does training with different versions of Tensorflow or pix2pix-tensorflow can affect the final results?
If so, which version/commit of Tensorflow/pix2pix-tensorflow do you suggest to use?
I used Tensorflow-gpu 1.8.0 for training on pix2pix-tensorflow (which I reset to april version with "git reset --hard d6f8e4ce00a1fd7a96a72ed17366bfcb207882c7"), the "export-checkpoint.py" file was missing from this april version, so I downloaded the last version for doing the export after the training.

**Comment by keijiro** [comment]
I think you have to use the same version of pix2pix-tensorflow for training and exporting. I mean you should use the latest version of pix2pix-tensorflow for training.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
