### ISSUE TITLE
Extracting edges from pictures with HED for free and offline

### ISSUE THREAD

**Issue by AndroXD** [keijiro/Pix2Pix#12]
Hello Keijiro,
Is there a method to extract edges from pictures with Holistically-Nested Edge Detection ( https://github.com/phillipi/pix2pix#extracting-edges ) without your Google Coolaboratory solution here: https://twitter.com/_kzr/status/1043154594468122624 ?
I tried to do it offline with this (  https://github.com/s9xie/hed#batch-processing ) and got to the point where I run "batch_hed.py" ( https://github.com/phillipi/pix2pix/blob/master/scripts/edges/batch_hed.py ) and all my pictures are converted into .MAT files (MATLAB) files, the final step requires to run "PostprocessHED.m" ( https://github.com/phillipi/pix2pix/blob/master/scripts/edges/PostprocessHED.m ) to convert them into normal pictures, but instructions says that I need MATLAB to do it: "get the cpp file edgesNmsMex.cpp from https://raw.githubusercontent.com/pdollar/edges/master/private/edgesNmsMex.cpp and compile it in Matlab: mex edgesNmsMex.cpp You also need to download and install Piotr's Computer Vision Matlab Toolbox:  https://pdollar.github.io/toolbox/"
Is there any method to do it for free? Matlab is a proprietary paid software, I noticed that your Coolaboratory is using Octave as a free alternative, how would I do it offline? I'm having trouble understanding how you managed to do it.
Any help is much appreciated, thank you very much for your kind attention!

**Comment by keijiro** [comment]
Unfortunately, I have no experience on running them offline. You should ask other experts. Sorry for not being helpful for you.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further issues.
