### ISSUE TITLE
Unity preprocessing pix2pix effect does not render as intended

### ISSUE THREAD

**Issue by Fqlox** [keijiro/Pix2Pix#16]
Hi,

I have some issues with the rendering in unity that differs from rendering it using python script.
I'm using my own model.

Here is a test ( from pix2pix python script using the unity camera as inputs : )  

![model_training](https://user-images.githubusercontent.com/33659731/129609921-07ba2730-90cf-4d2d-a13d-fb62d50617ef.PNG)

Here is the same scene using the unity pix2pix model as preprocessing effects:
![ca_jeu](https://user-images.githubusercontent.com/33659731/129610020-cbdbe0d2-ed55-4296-8f52-45b53282fb84.PNG)

![cap1](https://user-images.githubusercontent.com/33659731/129610007-020b477b-8e0c-49a0-a25e-669aac29d45a.PNG)

If you look closely, even if the python version is not train enough you can see difference between the sky, the wall and the floor. Whereas the Unity model blend all thing together. 

I don't know how I can improve these render

I'm using Unity 2018.2.8.1f on Windows 10

Thanks in advance

**Comment by keijiro** [comment]
> Here is the same scene 

That's the same scene but in a different aspect ratio. That difference may cause a problem.

By the way, I'm not actively working on this project any more. I'd recommend using [Barracuda](https://docs.unity3d.com/Packages/com.unity.barracuda@2.1/manual/index.html) instead for neural network inferencing.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Fqlox** [comment]
Thanks for the answer, I swapped to Label to _Street Scene segmentation_ models (to have a well train model) and changed material to match the color scheme of their segmentation. It still gives unmatching results, even when the aspect ratio is 1/1 (I did a build in 512x512 resolution)

**Comment by Fqlox** [comment]
I managed to get a better result. It appared that the postProcessing effect (in Pix2PixEffect.cs) has a edge detection that mess the render (I guess ?). I made a quick fix: line 102 with `cmd.BlitFullscreenTriangle(context.source, _sourceRT, sheet, 0);` replaced by `         cmd.BuiltinBlit(context.source, _sourceRT);`  and line 121 ` cmd.BlitFullscreenTriangle(_resultRT, context.destination, sheet, 1);` with `cmd.BuiltinBlit(_resultRT, context.destination);`
