### ISSUE TITLE
Model implementations

### ISSUE THREAD

**Issue by Yasakikondo74** [keijiro/Pix2Pix#17]
Hello Kejiro
Is it possible to use image model from civitai or huggingface website?
would love to see how community made models could work here.

**Comment by luciffer4521** [comment]
我已收到您的来信，谢谢！

**Comment by keijiro** [comment]
The model used in the sample is not made by me. Please contact the original author.

**Comment by Yasakikondo74** [comment]
no I mean like using the community models that published on civitai or huggingface websites. It's entirely made by the communities and as long as the creator set some ground rules of course but still, it would be nice to see some different vision that the Ai sees

**Comment by keijiro** [comment]
If you have pix2pix models, you can use them. However, as far as I know, CivitAI only provides StableDiffusion checkpoints, and it seems that the HuggingFace community isn’t really focused on pix2pix, since it’s quite an old architecture (introduced in 2016).
