### ISSUE TITLE
Output not as expected

### ISSUE THREAD

**Issue by aardappel** [keijiro/Pix2Pix#4]
https://imgur.com/a/XeEXZJC

This is on Windows 10, Nvidia 1080 Ti.

**Comment by keijiro** [comment]
Thanks for reporting the issue.

Are you trying the binary which I uploaded to the Released page? Or did you build it from the Unity project?

**Comment by aardappel** [comment]
From releases.. don't have Unity installed.

**Comment by keijiro** [comment]
Thanks. Then, could you provide `output_log.txt` file? It's located in `C:\Users\(user name)\AppData\LocalLow\DefaultCompany\Pix2Pix`. I'd like to look into the log file.

**Comment by aardappel** [comment]
```
Initialize engine version: 2018.2.6f1 (c591d9a97a0b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
    Vendor:   
    VRAM:     11132 MB
    Driver:   23.21.13.8859
Begin MonoManager ReloadAssembly
- Completed reload, in  0.148 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.435532 ms
Setting up 6 worker threads for Enlighten.
  Thread -> id: 36b4 -> priority: 1 
  Thread -> id: 62c8 -> priority: 1 
  Thread -> id: 62a4 -> priority: 1 
  Thread -> id: 4e54 -> priority: 1 
  Thread -> id: 21f4 -> priority: 1 
  Thread -> id: 53c8 -> priority: 1 

```

**Comment by keijiro** [comment]
Thanks. It seems to be initialized well, but the driver version looks like a little bit old. Could you try updating it?

**Comment by aardappel** [comment]
That seems to have fixed it!
