### ISSUE TITLE
Model format

### ISSUE THREAD

**Issue by Wenyi751** [keijiro/Pix2Pix#6]
Hello keijiro,
I've tried to trained my own model by https://github.com/affinelayer/pix2pix-tensorflow, and after training I got some data like 'checkpoint' and 'graph.pbtxt'. However I could not find the .pict data.
What should I do next to get the .pict data?

**Comment by keijiro** [comment]
You can export the checkpoint with using `tools/export-checkpoint.py`. Check the instruction in the `server` directory of the original repo.

https://github.com/affinelayer/pix2pix-tensorflow/tree/master/server

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by Wenyi751** [comment]
Cool, thank you!
