### ISSUE TITLE
Unity Problem

### ISSUE THREAD

**Issue by geest** [keijiro/Pix2Pix#7]
Hi Keijiro

I wonder if I could ask you a couple of questions about this? I saw your experiments on twitter, feeding it a render of some geometry and I'm really interested to try some thing out with it myself.

Unfortunately though I can't even get the demo scene to run. Could that be a problem with my GPU? I have a Quadro K400 which is good for heavy geometry and so on but is terrible for GPU rendering [Redshift / Octane etc]. I do have Direct X [12].

This is a grab of my Unity - as you can see refresh rate is 0...

![pix2pix_unity](https://user-images.githubusercontent.com/5301950/45431048-b0142b80-b69e-11e8-9594-7b351f72c96f.jpg)

I tried the pre-built binary too and that did sort of run but not as you'd expect. Grab also attached.

![pix2pix_prebuilt](https://user-images.githubusercontent.com/5301950/45431073-c1f5ce80-b69e-11e8-954a-ed61a77d2bcb.jpg)

Thanks very much for your time. It's fascinating work you're doing..

**Comment by keijiro** [comment]
I received the same report from some people (e.g. #4), and they're resolved by updating the display driver. Could you check if you're using the latest version of the NVIDIA driver?

**Comment by geest** [comment]
Hi
Thanks very much for the note. I've updated my drivers and that fixed it in the standalone version but Unity is still just blank...

**Comment by keijiro** [comment]
Have you put a `.pict` file in the `StreamingAssets` directory? You have to download `edges2cats_AtoB.pict` from [here](https://github.com/affinelayer/pix2pix-tensorflow-models) and put it in `Assets/StreamingAssets`. This file isn't included in the repository for some reasons.

**Comment by geest** [comment]
Ah - no I hadn't done that. I see now the same file is in the StreamingAssets folder of the standalone. It does work in Unity now - brilliant! Thanks

Is it very difficult to get it to use a different input, like the things you put up on twitter? Ie a render instead of a drawing. I'm curious to feed it some video for example.

**Comment by keijiro** [comment]
Please see #5. I'm working on it. You can try the WIP thing but it's quite messy at the moment.

**Comment by geest** [comment]
Many thanks, I will try that later.

**Comment by geest** [comment]
I couldn't figure out the postprocessing version, it's a bit beyond my understanding but I'll keep an eye on git / twitter if you're still working on it and maybe sometime soon I'll be able to grasp it..

Thanks though anyway, really interesting work.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
