### ISSUE TITLE
Null Reference Exception on UseCommandBuffer

### ISSUE THREAD

**Issue by abliss86** [keijiro/Pix2Pix#8]
Here's the full error:

`NullReferenceException: Object reference not set to an instance of an object
Pix2Pix.GpuBackend.UseCommandBuffer (UnityEngine.Rendering.CommandBuffer buffer) (at Assets/Pix2Pix/GpuBackend.cs:68)`

For the record, I'm on a Mac, using Unity 2017.3.  Any ideas?

**Comment by keijiro** [comment]
First of all, please check if `edges2cats_AtoB.pict` is correctly put in `Assets/StreamingAssets` directory (read "How to use a trained model" section in README).

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
