### ISSUE TITLE
How to export .pict model files?

### ISSUE THREAD

**Issue by jul-ya** [keijiro/Pix2Pix#9]
I wanted to try out your application with the CityScapes dataset (https://www.cityscapes-dataset.com/) but when I use the export python script, I get a human readable .bin file whilst the .pict file you use is in binary format. How do I convert the dataset into the format you use, or how to I export it properly to work with your application?

**Comment by keijiro** [comment]
Did you actually use this `export-checkpoint.py` script?

https://github.com/affinelayer/pix2pix-tensorflow/blob/master/server/tools/export-checkpoint.py

Although it has a human readable json header, the body part consists of binary data.

**Comment by jul-ya** [comment]
It worked after trying it on another computer, having tensorflow installed. Something has gone wrong at exporting, still not sure. Thanks anyways!
